sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/vnc-chrome-mvn
  - secure: Uie2kqKTsqiCyNuUGXJbRxRWrQziIn7TK9AHOozM1FkXH3hXDepHYFe9IRGx2JVj2fHLMKBetZL+AnnbySZkukiXf34xbW8fjMhDiuK6RM5iw1uZLurjnYWLN3OMDeuqKuVZDpgTaMGtlEdeybu3OtlqEKSLW0J68P4BlEn1wgKtQLHC3k/ImXpsuyu/UCtlLmvEX+59NweIiSvNpfNXzgOWt+nWGSvZ1lbcIyw7TwX9OMKkbBZlUnoZAqzJPEeasGQXTXsJ14eszCTNS7I2iTs5mS4IMlQ/ZCaycjQWXNP9WlVN49rrWDI2+32pSp5W29bfvHEoapjLkUQfq8WlI6mymPe4jq7DOWUOARYfaMr7OW+mPxMhn7TGgP6/JtlkUVUyAefyAY0c5zQHxNc2g9EJXG6lfl08RKh83rNrfFuu62gVoZwlsyFeE0/RFedns70SeYxOhspYcr/oSzQtRSWZLUvXDVg734SsPeQQaPtDCsIyzqkcTE7D10fn6eJhSkxjDUmJ8jCkPtnIqYEe+UmxsnEFlE51Tm5/9nEAA5rgRR5EmVcCHNwZfkY4ykcgvLtwiS1H30WAAFF9sPq7GfUMq4l4Sb+BfrPm6XaCcTJEQsiEE1viyhpNIdFuMNGfLQWFgvi3DNpjOdNyUJO9UWAPwspnuRQHAqNuZouaKMI=
  - secure: mE+0Ov8FHAb84lgtd3HNfeS4eZdmBcRu+qWvHoJTEiA/6eyZVuRiuVszS3J5eD2Y9wPwyEgr5Mdro8LgyuwUeIK1sKqsjsZrVa9Ie2Ng6naR09f3z++EWMyi7D808pK9HXKVD0IsQ9+jRFHGXAnNBhEtITsKoGLDOR8QfB22QC8weU3V+KGRqKXu7OZoU+mrNMVAvr7SCsa6FRChGXr8Y2+kDbJLmB9aAJmcu4msYpIVehqoGlSSNu+Z3QPeYSMeW/Skl14L2lk0rirAZtE7xWoN710pRg4TQBShgr/fPH2eS7Nl+yl6vHRuGJJLt4nZXlVGDjXWEwa5cOTWffRsfgjDb48lCQS7D63bhEx591op+qhw/+ygO+cTiLWHNyLjFr6caRooRsIIbhrqvQecGvVoW2YV86PSYI1F0M8JpSHwZjsBf+Inl9k9GyrrxOebLy7tKywRFq4sDv5p2Igrk+QBCBqZyMC0LQQzHePNi3AnRGpjyNX4DkRS6do7b3NJ/B4QLpscGdrcdqkdMhE3PmQwrDPA7u5ZVu4Nu3zC8CWqpzmE2KrXv//wWPCC5LmiXFSfcYRJXUeV5N3k60mu8c1YAsaY/rDCMGMaFoke25CawUlBj5CRKpWSvAhujLWsdELbrYDn5OYtbMP0F5HkQHR5V+yKfqECml+1NcZLWZQ=
before_script:
- cd image
- version="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
