sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/vnc-chrome-mvn
  - secure: tMTMR/P4nn8+WD21X1D+mCcUTuMA0R1aG2ot0i+nWE/qSu5APm+UrEVsm1bHHehkARvWZ09VuSinS2rW7mFqWQqOkD4NNe+PhK9+5YrHHrRzrjwLWmkoJ9IONzbXkpm9Jph3VnvzehJw2qHZKo4vyiDpCxD6W1gqZstXm7qsRuUU8kQ9ytggri+C6Dr7l3BtZPywJhpHG+w/hYU2Qvg0f0R4zaujszwijWFSJswP0Tz31zAwkRLvRn9n5sWWkTrTlO5UgQwiOEH6uqv+WJhB5S4HwDfxKLKYO54nC33M8BlTvwBIKIZuZh7RColNTAoAEzllAmQpqyYH/w0uYAOAq9KYG1Z8LHpQHQyxklGe/WxuXMu4DgS2IGEg3Bnd3kXLMNzdSULSxib3F/j9yG0lJp3B2BhzicreOf93YlCKLQ69+TYVsdMxQaj28aPIMkzzUl0ck0WF04auuL3o5ZMgIiA42gWbrRY0FH6LmRdhRBPT7XqUksf15dwf0x9yerGQmEPe+oQMpTX9HCSjPHcjGUOw3PNNPQtVW4B7SdAGnlWWCMSt5GaQNdATRVFlszRCKrRtSI+4w+y2DdJHggRAt1tD54mdjC5m8Biz9EEg+/mSrfZAbDoWyi0sHNnoQo9RWqmpWoZzB5UtKDgT2D9dWpZrNYd8Zc+AJRfof/QyAnE=
  - secure: PrqbUE+CcUxje1pbUMO5+NPXuYeA1jdZ71UxvUp5/3pyjjWdl3eqgDlUsBjKYutUXCMyf7EIlJ/PHqzQHnqp/UZ1/UtU7mOQvSq98ci0odalEJALaZyicbgZt46zQJiyBsHS6VBXAyOOUIyB50bvh3L1gy10DQj+5rgEOoJLV8TdyZm11FqBLpQqViFrr6sQR6KMAbvUoz1IrA8Db/Fi0hn2wSNcdu319KJAjVrbMLMFbj34fgBn/59OmIjW4mjQY9d+V4oLDooHSSh5TLhgENKww89RTyBlMG0Xym9p+ntTVI97pNwQMRAGBDMulJhKkWvnCjYLQsl3vCOTWbP/ukRCHtUe8yZ1KE0hkAcIHG073ER9iE8jVjq7f+mnAMx+ToU/J699zMerxC35mp1IxlyCfKLZnwwccnu93+ylAbFkAsJmPJszGIkbXPc5AEc7wyEFi1JFNkT2oSzdR7gC0HXq1JSLeby+mkAkbjcsVeWL9v2C65nBzOsdWwMxB8Lo1zmhecnQM+WcL8q45KP4T8lADxOdES45kq2jVMVBzZeMBrUUUiJAxDEJDm/rsJkR7Or6P7I2nUYWP6744dQC0nbsH+TKsfy/gsEr9845DigWG6dxQukU8zomG4lBYhXptNKcJWrDzri4oF0iyjzEySnK5u2QbdpwFVqjSFk+j+A=
before_script:
- cd image
- version="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
