sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/vnc-chrome-mvn
  - secure: gmTuUjJUrLxs3pi3AQudA55PoZ1dkkKWMXfvuiJ+3J77I7t7opJNra+JImrrWaabbrkC5+zPmH/OvNQhNHNTXcrwLEN3jkFSZqWatn1qAuMOB8CFOYs+9DWlc88oq6Qe2ZeBrh5LWzA/QEelrBobuwS8PEDzeyqb9Sc+gLyw7fvvnDlvQLNkIK4VgXXCejMLWS8ZvqXw7E3wLfuwxwJe+fixhZAGg6wfaGfNzYzy7PVLYcZHI7njxzcuxELHv/xG0FEiwttsxhFmJ7PgFITMgxY3aRW6p0uEWycvc+9j7bq8DHKyCppfYmyVFbMpj6ybfcJh9ENzCFo6MMRdSZnTfE2jxSCxTyAN4P1s8KWsJNDCgsQdXKaVl625gioKX9YwbD+DTodFTTZ+wCPQJufqbKKRUrDm1RuDqq7dO7I6E2eoWAz1OhFJZoLgoKUmtpPzuqjxFw1ugsAhKOkQyNZXdWpN2kPISu2i+L+EDqRMfnp4uXLWvc9nf4ZpsGLr9w6vhaiFOAzgo1AYj9NDJEDGDSWeDsWfCzY+Bqy3Q6GMrgiAXZmrA3m76dnxxbNEF2trm4ZyDZZgjt0EzfhSEbX3+XUCphOgi5abHHrybQ21wGHgjUogBUK5hVWLi14yx+wqJsPicn0qT3429eVf8DaOBRz8L+PKUM3zpJTHG6FExO0=
  - secure: o7LfVYYuyCT7+TuYQTy4S5giWqtjbhFDSZ0Ix+mW1CMwCR5f89XnN6Sa1aUbfv5YBOKUXCUTU3yqvXSBMr4E7/fxIPgUyF3XdizMPTbBhzjqQAd9qXIrZuwJgiqm5aTJiRFWx74jEj1tLEszXLSll1pRBB3IlJGRxOHfs7vFqDb0FS6x+hOTf0bGmd3o0KV5l7cyQqciv2gKIFSyQ0sZ0mahPRTKu3a7kLDaVFkh546nret6Oco+z1qv8gmBHBxD3ZrHIDRky3RJwqGFvEYg1pEhxMDpotVHZdtF6DkFoF/D5lmmLpxYeFFe+1bYFAg3i4+lz+5ups9fO9BYAj5wXMT7cifntjYXPNXmjsGf09GRpgTv2LPdHCkNzUEFvrWjpJP1v5g9GaGm03dXcmJtc4YrXbjLX4xM/KND7agUpQupRASV6Sij8C1d59NSXQiO7fN4ZKaA6XMBPEYUw0Pb3fT4YTEXkBugD4tSjYqTSR5TAy6fljWHhVkMShh7HcQqbFY5FT/aU90MJa4iU25zZzQPfpcvoFAmnXn7V+BoipGP4oBYswE40dX3CMa4mw+JdwCUT/1jx8ifuecIRq2mTiNhE4NT8Vie8dxP88RL0UNkvbI2b9a4IymTFmEJxzeagYYvu8PK52s6+GOq6OQd57ODNls1IP2oPUTVvGIkNTE=
before_script:
- cd image
- version="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
