sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/vnc-chrome-mvn
  - secure: ghIMTz7afhqtX4cF4BAd5VZTq9aSm+HJ099ISiFsAM6NX89FHQuDKrTGzpbD7R6fcBCpGVqRzJcsM1HgzurTc2c8L5lJ2tOKOqjp8hL/rL/CM9/LEIR9knkSwsQ3HnE4xMzzzzoAtd2zCx8GB7sQxkM5rSV1r3w2FswNIMNutkiovtvhEP7RVDKP9VIY/VEqYZaZDV0AqxSomQ6QmKiCHbr1y0AhCUSQaZmD+VC0gMeBEF8UucIymVJ7D2DZPRElvJV77fRWHoPUKG2CA9MGlDExJgEXDBwAHbq1jl7XJ2sO49fnTauC3SbhmfWGNfhB898RlXrffUxxJOU26tQGf7+7b8Y1oIKMFTkh2CkgI076rKckkku+goSyO/YO94LMqSDY3soQAGwOyUWyCEpDgEl1XW6JysGFiXXg2XdYrPSlnmQ4R7PTOraqyupqZKnGM7+AO+aPoV+MpdLgxU/5Pd3GVXmoG7+wu897E/G4HJCTdqpP7CLksBoRtp3E2IKF6UU/bfmXOQMUh/hNdoYlhMlmCVKUqBs9urppiAgpqM+wXDnJBGpXGH71Kh0ZuXqzdjeuByOYCKgHEZlx1qnih+ZggKAEncNiwmPa6jFMQ/PhD9ZyGRUM4QtHmlyS/+retOBMaoKYCfzn59RaR8EbKeo+FSpDiDmAOREk3USTtMg=
  - secure: QzR00f8pHMZ9iEiYfRnPF0eL9aDj+cOw62oEXPTSP42VVvmYSWwXYUvLX7B1g3ZSKoYzQ1Y1ocFHLnZBj8ijSERCVZLLJ/RwIOX9K5+ELvNMbJ0ZkCDZ/MsLnWteALd+NCfduQX6gM8uQDHlnusxYxhzb478ualiY3toqmKrxXeF729gb6edNblp7NUQgf6yFpDKdpQc28a9RF3/wpNK73PNQm4MX5CqhHL4L5NbtwIxtGIJaWwzthJXkVIo5yFY4G5ByArZJ51jkp46Kbe5yggQzNg3fPCvMlQxlH1vH5IgOo1XmbM+Q439XGOLYQjjqiGvDNyT82STXnIrL1Pvjkfs6rnSEeN2m5FezHc9cJUGDiQ48EPQT7uPPAcWjugutJRQPzHF+67z+q+JnFvDXC3z/A9WyHir7DDS7ytI6hwKb90wA+GtAOy/gag3SzwWzVtrbH4HVDiD7Pjq7TQjBTbhu2Tv4I80+JPThPCQiZjTZFfL4MQQMLON/CqxQfdbZGz21/LLHpwzwZjqbVnx6iqCbOCse61JI9FcPFfPoVlYPItBOfZgj8nUnZiH8RMVFkYnujARXojWr1ARA5YAO5VHgtYZWhbfYXcDiUAvXWAoFTohH6NIyvw+o7YlP1hK6UTv9KcjPB9D3pAcbdh0SnHQpqZkY+jGeWzPJ49ILJQ=
before_script:
- cd image
- version="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" -f "Dockerfile" .
after_script:
- docker images
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master